# Generated by Django 4.2.1 on 2023-05-26 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('average', 'Avergage'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=30, null=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('video_urls', models.JSONField(blank=True, null=True)),
                ('price_of_review', models.DecimalField(decimal_places=10, max_digits=19)),
                ('payment_of_connector', models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('unpaid', 'Unpaid')], max_length=30, null=True)),
                ('payment_of_product_user', models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('unpaid', 'Unpaid')], max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.credentialsdata')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.model')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_modified_by', to='users.credentialsdata')),
                ('ques_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.questioncluster')),
                ('review_of_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primary.productuser')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primary.platformanduserconnector')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe'), ('paytm', 'Paytm')], max_length=30)),
                ('payment_method', models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe'), ('paytm', 'Paytm')], max_length=30)),
                ('payment_date', models.DateTimeField()),
                ('payment_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('payment_due_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('unpaid', 'Unpaid')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.credentialsdata')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_for_review_modified_by', to='users.credentialsdata')),
                ('payment_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_payment', to='users.credentialsdata')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOfReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_ids', models.JSONField()),
                ('gst', models.DecimalField(decimal_places=10, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_review', to='users.credentialsdata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.credentialsdata')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_of_review_modified_by', to='users.credentialsdata')),
            ],
        ),
    ]
