# Generated by Django 4.2.1 on 2023-06-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primary.brand'),
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primary.category'),
        ),
        migrations.AlterField(
            model_name='review',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primary.model'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ques_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primary.questioncluster'),
        ),
    ]
